version: "3.8"

services:
    database_msl:
        image: postgres
        container_name: msl_postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=msl
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: msl
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database_msl
        depends_on:
            - database_msl


volumes:
    pgdata:
        driver: local

